use super::{KnownProblemCode, Metadata, RecoveryStrategy, ResourceKind, WebSocketAction};

pub(super) fn metadata(code: KnownProblemCode) -> Option<Metadata> {
	match code {
		KnownProblemCode::AccountFrozen => Some(Metadata {
			title: "Account frozen",
			detail: Some(
				"Trading on your account is paused right now. Contact support to find out more.",
			),
			status: Some(403),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::AccountQuarantined => Some(Metadata {
			title: "Account quarantined",
			detail: Some("Your account is under review. Contact support for more details."),
			status: Some(403),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::BatchInFlight => Some(Metadata {
			title: "Something is still processing",
			detail: Some(
				"An earlier split or merge is still going through. Please wait a moment and try again.",
			),
			status: Some(409),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::BatchNotFound => Some(Metadata {
			title: "Batch not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::BatchSuperseded => Some(Metadata {
			title: "Batch superseded",
			detail: Some("A newer batch replaced this batch."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::CategoryNotFound => Some(Metadata {
			title: "Category not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::ChainExecutionFailed => Some(Metadata {
			title: "Chain execution failed",
			detail: Some("Transaction failed, please retry."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::CredentialsMissing => Some(Metadata {
			title: "Credentials required",
			detail: None,
			status: Some(401),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::None),
		}),
		KnownProblemCode::DependencyCredentialsRejected => Some(Metadata {
			title: "Dependency credentials rejected",
			detail: Some("Third-party service authorization failed, please try again later."),
			status: Some(502),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::DependencyInvalidResponse => Some(Metadata {
			title: "Dependency returned an invalid response",
			detail: Some(
				"Third-party service returned an invalid response, please try again later.",
			),
			status: Some(502),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::DependencyOutcomeUnknown => Some(Metadata {
			title: "Submission status is uncertain",
			detail: Some(
				"Your request may have succeeded. Check your positions before trying again.",
			),
			status: Some(502),
			recovery: RecoveryStrategy::CheckStatus,
			resource: Some(ResourceKind::Batch),
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::DependencyUnavailable => Some(Metadata {
			title: "Dependency temporarily unavailable",
			detail: Some("A third-party service is down, please try again later."),
			status: Some(503),
			recovery: RecoveryStrategy::Retry,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::Reconnect),
		}),
		KnownProblemCode::DuplicateOrder => Some(Metadata {
			title: "Duplicate order",
			detail: Some("An order with this identity already exists."),
			status: Some(409),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::EndpointRetired => Some(Metadata {
			title: "Endpoint retired",
			detail: Some("This endpoint is no longer available."),
			status: Some(410),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::EventNotFound => Some(Metadata {
			title: "Event not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::FeatureNotConfigured => Some(Metadata {
			title: "This feature is not available here",
			detail: Some("This option is not turned on in this environment."),
			status: Some(503),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::ForbiddenScope => Some(Metadata {
			title: "Permission denied",
			detail: None,
			status: Some(403),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::None),
		}),
		KnownProblemCode::GroupNotFound => Some(Metadata {
			title: "Batch group not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::IdentityTokenExpired => Some(Metadata {
			title: "Your session has expired",
			detail: Some("Please log in again to continue."),
			status: Some(401),
			recovery: RecoveryStrategy::RefreshIdentityToken,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::Reconnect),
		}),
		KnownProblemCode::InsufficientBalance => Some(Metadata {
			title: "Insufficient balance",
			detail: Some("Available balance is lower than the order value."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::InsufficientShares => Some(Metadata {
			title: "Insufficient shares",
			detail: Some("Available shares are lower than the requested amount."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::InternalError => Some(Metadata {
			title: "Something went wrong",
			detail: Some("We hit an unexpected problem. Please try again in a moment."),
			status: Some(500),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::Reconnect),
		}),
		KnownProblemCode::InvalidBatch => Some(Metadata {
			title: "Invalid batch",
			detail: Some("The batch does not satisfy submission requirements."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::InvalidIdentityToken => Some(Metadata {
			title: "Invalid identity token",
			detail: None,
			status: Some(401),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::None),
		}),
		KnownProblemCode::InvalidMessage => Some(Metadata {
			title: "Invalid WebSocket message",
			detail: Some("The message is not valid for this connection."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::None),
		}),
		KnownProblemCode::InvalidPathParameter => Some(Metadata {
			title: "Invalid path parameter",
			detail: Some("One or more path parameters are invalid."),
			status: Some(400),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::InvalidPersonalAccessToken => Some(Metadata {
			title: "Invalid personal access token",
			detail: None,
			status: Some(401),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::None),
		}),
		KnownProblemCode::InvalidServiceCredential => Some(Metadata {
			title: "Invalid service credential",
			detail: None,
			status: Some(401),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::InvalidSignature => Some(Metadata {
			title: "Invalid signature",
			detail: Some("The submitted signature could not be verified."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::LpPayoutNotRecoverable => Some(Metadata {
			title: "LP payout cannot be resumed",
			detail: Some("This LP payout run cannot be resumed from its current state."),
			status: Some(409),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::LpPayoutRunNotFound => Some(Metadata {
			title: "LP payout run not found",
			detail: Some("The requested LP payout run does not exist."),
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::MalformedJson => Some(Metadata {
			title: "Malformed JSON",
			detail: Some("The request body is not valid JSON."),
			status: Some(400),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::MalformedWebsocketMessage => Some(Metadata {
			title: "Malformed WebSocket message",
			detail: Some("The WebSocket message is not valid JSON."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::None),
		}),
		KnownProblemCode::MarketClosed => Some(Metadata {
			title: "Market closed",
			detail: Some("Market is not accepting orders."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::None),
		}),
		KnownProblemCode::MarketNotFound => Some(Metadata {
			title: "Market not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::MethodNotAllowed => Some(Metadata {
			title: "Method not allowed",
			detail: Some("This route does not support the requested method."),
			status: Some(405),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::OrderExpirationTooSoon => Some(Metadata {
			title: "Order expiration too soon",
			detail: Some("Good-til-date orders must expire at least 30 seconds from now."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::OrderFundingFailed => Some(Metadata {
			title: "Order funding failed",
			detail: Some("Order not successful, please try again."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::OrderNotCancellable => Some(Metadata {
			title: "Order cannot be cancelled",
			detail: Some("The order is no longer cancellable."),
			status: Some(409),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::OrderNotFillable => Some(Metadata {
			title: "Order cannot be filled",
			detail: Some("Order cannot be filled right now."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::OrderNotFound => Some(Metadata {
			title: "Order not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		KnownProblemCode::OrderPriceOutOfRange => Some(Metadata {
			title: "Order price out of range",
			detail: Some("Limit price must be above 0 and below 1 collateral unit."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		}),
		_ => None,
	}
}
