use super::{KnownProblemCode, Metadata, RecoveryStrategy, WebSocketAction};

pub(super) fn metadata(code: KnownProblemCode) -> Metadata {
	match code {
		KnownProblemCode::OrderSizeAboveMaximum => Metadata {
			title: "Order size above maximum",
			detail: Some("Maximum market sell size is 100,000 shares."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::OrderSizeBelowMinimum => Metadata {
			title: "Order size below minimum",
			detail: Some("Minimum market sell size is 1 share."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::OrderSubmissionFailed => Metadata {
			title: "Order submission failed",
			detail: Some("Order could not be submitted, please try again later."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::OrderValueAboveMaximum => Metadata {
			title: "Order value above maximum",
			detail: Some("Maximum order value is $100,000."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::OrderValueBelowMinimum => Metadata {
			title: "Order value below minimum",
			detail: Some("Minimum order value is $0.10."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::PnlNotReady => Metadata {
			title: "PnL not ready",
			detail: Some("PnL is not available yet."),
			status: Some(425),
			recovery: RecoveryStrategy::Retry,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::PnlUnavailable => Metadata {
			title: "PnL unavailable",
			detail: Some("PnL is unavailable for this wallet."),
			status: Some(503),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::PostOnlyWouldCross => Metadata {
			title: "Post-only order would cross",
			detail: Some("The order would execute immediately instead of resting."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::PriceFeedNotFound => Metadata {
			title: "Price feed not found",
			detail: Some("No price feed is configured for the requested security and provider."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::PriceServiceNotConfigured => Metadata {
			title: "Price service not configured",
			detail: Some("The price service is not configured on this deployment."),
			status: Some(503),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::PriceStreamCapacityExceeded => Metadata {
			title: "Price stream capacity exceeded",
			detail: Some("The shared price-stream symbol limit has been reached."),
			status: Some(503),
			recovery: RecoveryStrategy::Retry,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::PriceStreamNotConfigured => Metadata {
			title: "Price stream not configured",
			detail: Some("Price streaming is not configured on this deployment."),
			status: Some(503),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::PriceTemporarilyUnavailable => Metadata {
			title: "Price temporarily unavailable",
			detail: Some("The requested price is not available yet."),
			status: Some(503),
			recovery: RecoveryStrategy::Retry,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::ProfileNotFound => Metadata {
			title: "Profile not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::RateLimited => Metadata {
			title: "Too many requests",
			detail: Some("You are rate limited, please try again later."),
			status: Some(429),
			recovery: RecoveryStrategy::RetryAfter,
			resource: None,
			origin: true,
			edge: true,
			websocket: None,
		},
		KnownProblemCode::RequestBodyTooLarge => Metadata {
			title: "Request body too large",
			detail: None,
			status: Some(413),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::RouteNotFound => Metadata {
			title: "Route not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::SecurityNotFound => Metadata {
			title: "Security not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::SequenceConflict => Metadata {
			title: "Sequence conflict",
			detail: Some("Order submission failed, please retry."),
			status: Some(409),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::ServerRestarting => Metadata {
			title: "Server restarting",
			detail: Some("The server is restarting. Reconnect after a short delay."),
			status: None,
			recovery: RecoveryStrategy::Retry,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::Reconnect),
		},
		KnownProblemCode::SettlementDivergent => Metadata {
			title: "Settlement requires review",
			detail: Some("Settlement effects do not match the expected operation set."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::SettlementsPending => Metadata {
			title: "Settlements pending",
			detail: Some(
				"Fills for this market can still settle; payouts are held until they drain.",
			),
			status: Some(409),
			recovery: RecoveryStrategy::Retry,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::SignerAuthorizationRequired => Metadata {
			title: "Finish wallet setup",
			detail: Some("Complete the wallet approval step, then try again."),
			status: Some(424),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::SlowConsumer => Metadata {
			title: "Client is reading too slowly",
			detail: Some(
				"The connection was closed because messages were not read quickly enough.",
			),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::Reconnect),
		},
		KnownProblemCode::StreamSubjectNotFound => Metadata {
			title: "Stream subject not found",
			detail: None,
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::None),
		},
		KnownProblemCode::StreamSubjectUnavailable => Metadata {
			title: "Stream subject temporarily unavailable",
			detail: Some("This stream subject is temporarily unavailable."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::Resubscribe),
		},
		KnownProblemCode::SubscriptionLimitExceeded => Metadata {
			title: "Subscription limit exceeded",
			detail: None,
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::None),
		},
		KnownProblemCode::TokenNotFound => Metadata {
			title: "Token not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::TradingDayNotFound => Metadata {
			title: "Trading day not found",
			detail: Some("No trading-day coverage exists for the requested date."),
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::UnsupportedMediaType => Metadata {
			title: "Unsupported media type",
			detail: Some("Send the request body as application/json."),
			status: Some(415),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::UnsupportedWebsocketData => Metadata {
			title: "Unsupported WebSocket data",
			detail: Some("Send WebSocket messages as JSON text frames."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::None),
		},
		KnownProblemCode::ValidationFailed => Metadata {
			title: "Request validation failed",
			detail: Some("One or more fields are invalid."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::ValueCapExceeded => Metadata {
			title: "Value cap exceeded",
			detail: Some("Order value exceeds the configured maximum cap."),
			status: Some(422),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::VenueNotFound => Metadata {
			title: "Venue not found",
			detail: None,
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::WalletNotRegistered => Metadata {
			title: "Wallet not registered",
			detail: Some("Finish wallet registration and then retry."),
			status: Some(404),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::WalletSetupFailed => Metadata {
			title: "Wallet setup failed",
			detail: Some("Wallet setup did not complete successfully."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::WalletSetupIncomplete => Metadata {
			title: "Wallet setup incomplete",
			detail: Some("Finish wallet registration and then retry."),
			status: Some(424),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::None),
		},
		KnownProblemCode::WalletSetupOutcomeUnknown => Metadata {
			title: "Wallet setup outcome is uncertain",
			detail: Some("Wallet setup may have been submitted and requires reconciliation."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::WebsocketMessageTooLarge => Metadata {
			title: "WebSocket message too large",
			detail: None,
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::None),
		},
		KnownProblemCode::WebsocketProtocolError => Metadata {
			title: "WebSocket protocol error",
			detail: Some("The WebSocket protocol state is invalid."),
			status: None,
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: false,
			edge: false,
			websocket: Some(WebSocketAction::None),
		},
		KnownProblemCode::WebsocketUpgradeRequired => Metadata {
			title: "WebSocket upgrade required",
			detail: Some("This route requires a WebSocket upgrade."),
			status: Some(426),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: None,
		},
		KnownProblemCode::WrongCredentialType => Metadata {
			title: "Wrong credential type",
			detail: None,
			status: Some(401),
			recovery: RecoveryStrategy::None,
			resource: None,
			origin: true,
			edge: false,
			websocket: Some(WebSocketAction::None),
		},
		_ => core::unreachable!("registered metadata partition must cover every known code"),
	}
}
