"""Generate transport-parity methods from the canonical synchronous client."""

import argparse
import ast
import subprocess
import sys
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true", help="verify generated output without writing")
arguments = parser.parse_args()
ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / "agara_sdk/client.py").read_text()
module = ast.parse(source)
client = next(node for node in module.body if isinstance(node, ast.ClassDef))
excluded = {
    "__init__",
    "_request",
    "close",
    "__enter__",
    "__exit__",
    "stream_prices",
    "stream_pyth_price",
}
methods = [
    node for node in client.body if isinstance(node, ast.FunctionDef) and node.name not in excluded
]
async_names = {node.name for node in methods} | {"_request"}


class Asyncify(ast.NodeTransformer):
    def visit_Call(self, node):
        node = self.generic_visit(node)
        if isinstance(node.func, ast.Attribute):
            if (
                isinstance(node.func.value, ast.Name)
                and node.func.value.id == "self"
                and node.func.attr in async_names
            ):
                return ast.Await(value=node)
            if (
                isinstance(node.func.value, ast.Name)
                and node.func.value.id == "time"
                and node.func.attr == "sleep"
            ):
                node.func.value.id = "asyncio"
                return ast.Await(value=node)
        return node


header = '''"""Async current-trader client; method bodies generated by tools/generate_async.py."""
from __future__ import annotations

import asyncio
from typing import TYPE_CHECKING, Any, Literal, cast
from collections.abc import AsyncIterator

import httpx

from . import catalogue, models
from .amounts import Amount, positive_micro
from .errors import AgaraError, ProtocolError, TransportError, _raise_api_error
from ._requests import DEFAULT_BASE_URL, _compact, _segment, _validate_order, _validate_batch, _limit_body, _market_body, batch_is_terminal
from ._http import validate_settings, require_auth, request_timeout, check_deadline
from .client import _deadline, _remaining_sleep
from .prices import PriceEvent, aiter_prices

if TYPE_CHECKING:
    from .signing import SignedOrder, SignedOrderEntry


class AsyncAgaraClient:
    """Native async HTTP; injected httpx clients remain owned by the caller."""

    def __init__(self, token: str | None = None, base_url: str = DEFAULT_BASE_URL,
                 timeout: float = 10.0, client: httpx.AsyncClient | None = None):
        validate_settings(base_url, timeout)
        self._token = token
        self.base_url = base_url.rstrip('/')
        self.timeout = timeout
        self._owns_client = client is None
        self._client = client if client is not None else httpx.AsyncClient(timeout=timeout)
        self._headers = {'Accept': 'application/json', 'Content-Type': 'application/json'}
        if token:
            self._headers['Authorization'] = f'Bearer {token}'

    async def _request(self, method: str, path: str, json: Any = None, params: Any = None, deadline: float | None = None) -> Any:
        require_auth(path, self._token)
        timeout = request_timeout(self.timeout, deadline)
        try:
            response = await asyncio.wait_for(self._client.request(method, self.base_url + path, json=json,
                params=params, headers=self._headers, timeout=timeout, follow_redirects=False), timeout=timeout)
        except (httpx.TransportError, asyncio.TimeoutError) as exc:
            check_deadline(deadline)
            raise TransportError(method, exc) from exc
        check_deadline(deadline)
        if not 200 <= response.status_code < 300:
            try:
                error_body = response.json()
            except ValueError:
                error_body = response.text
            _raise_api_error(response.status_code, error_body, response.headers)
        if not response.content:
            return None
        try:
            value = response.json()
        except ValueError as exc:
            raise ProtocolError('successful response contained invalid JSON') from exc
        if not isinstance(value, dict):
            raise ProtocolError('successful response was not a JSON object')
        return value

'''
for method in methods:
    method = Asyncify().visit(method)
    method = ast.AsyncFunctionDef(
        name=method.name,
        args=method.args,
        body=method.body,
        decorator_list=method.decorator_list,
        returns=method.returns,
        type_comment=None,
    )
    ast.fix_missing_locations(method)
    header += "\n".join("    " + line for line in ast.unparse(method).splitlines()) + "\n\n"
header += '''    def stream_prices(self, symbols: list[str]) -> AsyncIterator[PriceEvent]:
        """Demand-driven SSE; aclose the iterator on early exit."""
        return aiter_prices(self._client, self.base_url, self._headers, self.timeout, symbols=symbols)

    def stream_pyth_price(self, symbol: str) -> AsyncIterator[PriceEvent]:
        """Stream one provider symbol on the single-symbol SSE endpoint."""
        return aiter_prices(self._client, self.base_url, self._headers, self.timeout, symbol=symbol)

    async def aclose(self) -> None:
        if self._owns_client:
            await self._client.aclose()

    async def __aenter__(self) -> AsyncAgaraClient:
        return self

    async def __aexit__(self, *_exc: Any) -> None:
        await self.aclose()
'''
output = ROOT / "agara_sdk/aio.py"
for command in [
    ["check", "--select", "I", "--fix"],
    ["format"],
]:
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            *command,
            "--config",
            str(ROOT / "pyproject.toml"),
            "--stdin-filename",
            str(output),
            "-",
        ],
        input=header,
        text=True,
        capture_output=True,
        check=True,
    )
    header = result.stdout
if arguments.check:
    if output.read_text() != header:
        sys.exit("agara_sdk/aio.py is stale; run tools/generate_async.py")
else:
    output.write_text(header)
