"""Problem metadata pinned to platform a7e8c2d specs/problem-contracts/problem-codes.json."""

from typing import Any

METADATA: dict[str, dict[str, Any]] = {
    "account_frozen": {
        "async_persistable": False,
        "code": "account_frozen",
        "http_status": 403,
        "public_detail": "Trading on your account is paused right now. Contact support "
        "to find out more.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Account frozen",
        "urn": "urn:agara:problem:account-frozen",
        "websocket": None,
    },
    "account_quarantined": {
        "async_persistable": False,
        "code": "account_quarantined",
        "http_status": 403,
        "public_detail": "Your account is under review. Contact support for more details.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Account quarantined",
        "urn": "urn:agara:problem:account-quarantined",
        "websocket": None,
    },
    "batch_in_flight": {
        "async_persistable": False,
        "code": "batch_in_flight",
        "http_status": 409,
        "public_detail": "An earlier split or merge is still going through. Please "
        "wait a moment and try again.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Something is still processing",
        "urn": "urn:agara:problem:batch-in-flight",
        "websocket": None,
    },
    "batch_not_found": {
        "async_persistable": False,
        "code": "batch_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Batch not found",
        "urn": "urn:agara:problem:batch-not-found",
        "websocket": None,
    },
    "batch_superseded": {
        "async_persistable": True,
        "code": "batch_superseded",
        "http_status": None,
        "public_detail": "A newer batch replaced this batch.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async"],
        "title": "Batch superseded",
        "urn": "urn:agara:problem:batch-superseded",
        "websocket": None,
    },
    "category_not_found": {
        "async_persistable": False,
        "code": "category_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Category not found",
        "urn": "urn:agara:problem:category-not-found",
        "websocket": None,
    },
    "chain_execution_failed": {
        "async_persistable": True,
        "code": "chain_execution_failed",
        "http_status": None,
        "public_detail": "Transaction failed, please retry.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async"],
        "title": "Chain execution failed",
        "urn": "urn:agara:problem:chain-execution-failed",
        "websocket": None,
    },
    "credentials_missing": {
        "async_persistable": False,
        "code": "credentials_missing",
        "http_status": 401,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http", "websocket"],
        "title": "Credentials required",
        "urn": "urn:agara:problem:credentials-missing",
        "websocket": {"action": "none", "close_code": 1008},
    },
    "dependency_credentials_rejected": {
        "async_persistable": False,
        "code": "dependency_credentials_rejected",
        "http_status": 502,
        "public_detail": "Third-party service authorization failed, please try again later.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Dependency credentials rejected",
        "urn": "urn:agara:problem:dependency-credentials-rejected",
        "websocket": None,
    },
    "dependency_invalid_response": {
        "async_persistable": False,
        "code": "dependency_invalid_response",
        "http_status": 502,
        "public_detail": "Third-party service returned an invalid "
        "response, please try again later.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Dependency returned an invalid response",
        "urn": "urn:agara:problem:dependency-invalid-response",
        "websocket": None,
    },
    "dependency_outcome_unknown": {
        "async_persistable": False,
        "code": "dependency_outcome_unknown",
        "http_status": 502,
        "public_detail": "Your request may have succeeded. Check your "
        "positions before trying again.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"resource_kind": "batch", "strategy": "check_status"},
        "representations": ["origin_http"],
        "title": "Submission status is uncertain",
        "urn": "urn:agara:problem:dependency-outcome-unknown",
        "websocket": None,
    },
    "dependency_unavailable": {
        "async_persistable": False,
        "code": "dependency_unavailable",
        "http_status": 503,
        "public_detail": "A third-party service is down, please try again later.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "retry"},
        "representations": ["origin_http", "websocket"],
        "title": "Dependency temporarily unavailable",
        "urn": "urn:agara:problem:dependency-unavailable",
        "websocket": {"action": "reconnect", "close_code": 1013},
    },
    "duplicate_order": {
        "async_persistable": False,
        "code": "duplicate_order",
        "http_status": 409,
        "public_detail": "An order with this identity already exists.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Duplicate order",
        "urn": "urn:agara:problem:duplicate-order",
        "websocket": None,
    },
    "endpoint_retired": {
        "async_persistable": False,
        "code": "endpoint_retired",
        "http_status": 410,
        "public_detail": "This endpoint is no longer available.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Endpoint retired",
        "urn": "urn:agara:problem:endpoint-retired",
        "websocket": None,
    },
    "event_not_found": {
        "async_persistable": False,
        "code": "event_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Event not found",
        "urn": "urn:agara:problem:event-not-found",
        "websocket": None,
    },
    "feature_not_configured": {
        "async_persistable": False,
        "code": "feature_not_configured",
        "http_status": 503,
        "public_detail": "This option is not turned on in this environment.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "This feature is not available here",
        "urn": "urn:agara:problem:feature-not-configured",
        "websocket": None,
    },
    "forbidden_scope": {
        "async_persistable": False,
        "code": "forbidden_scope",
        "http_status": 403,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http", "websocket"],
        "title": "Permission denied",
        "urn": "urn:agara:problem:forbidden-scope",
        "websocket": {"action": "none", "close_code": 1008},
    },
    "group_not_found": {
        "async_persistable": False,
        "code": "group_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Batch group not found",
        "urn": "urn:agara:problem:group-not-found",
        "websocket": None,
    },
    "identity_token_expired": {
        "async_persistable": False,
        "code": "identity_token_expired",
        "http_status": 401,
        "public_detail": "Please log in again to continue.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "refresh_identity_token"},
        "representations": ["origin_http", "websocket"],
        "title": "Your session has expired",
        "urn": "urn:agara:problem:identity-token-expired",
        "websocket": {"action": "reconnect", "close_code": 4001},
    },
    "insufficient_balance": {
        "async_persistable": True,
        "code": "insufficient_balance",
        "http_status": 422,
        "public_detail": "Available balance is lower than the order value.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async", "origin_http", "websocket"],
        "title": "Insufficient balance",
        "urn": "urn:agara:problem:insufficient-balance",
        "websocket": None,
    },
    "insufficient_shares": {
        "async_persistable": True,
        "code": "insufficient_shares",
        "http_status": 422,
        "public_detail": "Available shares are lower than the requested amount.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async", "origin_http", "websocket"],
        "title": "Insufficient shares",
        "urn": "urn:agara:problem:insufficient-shares",
        "websocket": None,
    },
    "internal_error": {
        "async_persistable": True,
        "code": "internal_error",
        "http_status": 500,
        "public_detail": "We hit an unexpected problem. Please try again in a moment.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async", "origin_http", "websocket"],
        "title": "Something went wrong",
        "urn": "urn:agara:problem:internal-error",
        "websocket": {"action": "reconnect", "close_code": 1011},
    },
    "invalid_batch": {
        "async_persistable": False,
        "code": "invalid_batch",
        "http_status": 422,
        "public_detail": "The batch does not satisfy submission requirements.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Invalid batch",
        "urn": "urn:agara:problem:invalid-batch",
        "websocket": None,
    },
    "invalid_identity_token": {
        "async_persistable": False,
        "code": "invalid_identity_token",
        "http_status": 401,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http", "websocket"],
        "title": "Invalid identity token",
        "urn": "urn:agara:problem:invalid-identity-token",
        "websocket": {"action": "none", "close_code": 1008},
    },
    "invalid_message": {
        "async_persistable": False,
        "code": "invalid_message",
        "http_status": None,
        "public_detail": "The message is not valid for this connection.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["websocket"],
        "title": "Invalid WebSocket message",
        "urn": "urn:agara:problem:invalid-message",
        "websocket": {"action": "none", "close_code": 1008},
    },
    "invalid_path_parameter": {
        "async_persistable": False,
        "code": "invalid_path_parameter",
        "http_status": 400,
        "public_detail": "One or more path parameters are invalid.",
        "public_detail_policy": "allowlisted_typed",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Invalid path parameter",
        "urn": "urn:agara:problem:invalid-path-parameter",
        "websocket": None,
    },
    "invalid_personal_access_token": {
        "async_persistable": False,
        "code": "invalid_personal_access_token",
        "http_status": 401,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http", "websocket"],
        "title": "Invalid personal access token",
        "urn": "urn:agara:problem:invalid-personal-access-token",
        "websocket": {"action": "none", "close_code": 1008},
    },
    "invalid_service_credential": {
        "async_persistable": False,
        "code": "invalid_service_credential",
        "http_status": 401,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Invalid service credential",
        "urn": "urn:agara:problem:invalid-service-credential",
        "websocket": None,
    },
    "invalid_signature": {
        "async_persistable": False,
        "code": "invalid_signature",
        "http_status": 422,
        "public_detail": "The submitted signature could not be verified.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Invalid signature",
        "urn": "urn:agara:problem:invalid-signature",
        "websocket": None,
    },
    "lp_payout_not_recoverable": {
        "async_persistable": False,
        "code": "lp_payout_not_recoverable",
        "http_status": 409,
        "public_detail": "This LP payout run cannot be resumed from its current state.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "LP payout cannot be resumed",
        "urn": "urn:agara:problem:lp-payout-not-recoverable",
        "websocket": None,
    },
    "lp_payout_run_not_found": {
        "async_persistable": False,
        "code": "lp_payout_run_not_found",
        "http_status": 404,
        "public_detail": "The requested LP payout run does not exist.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "LP payout run not found",
        "urn": "urn:agara:problem:lp-payout-run-not-found",
        "websocket": None,
    },
    "malformed_json": {
        "async_persistable": False,
        "code": "malformed_json",
        "http_status": 400,
        "public_detail": "The request body is not valid JSON.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Malformed JSON",
        "urn": "urn:agara:problem:malformed-json",
        "websocket": None,
    },
    "malformed_websocket_message": {
        "async_persistable": False,
        "code": "malformed_websocket_message",
        "http_status": None,
        "public_detail": "The WebSocket message is not valid JSON.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["websocket"],
        "title": "Malformed WebSocket message",
        "urn": "urn:agara:problem:malformed-websocket-message",
        "websocket": {"action": "none", "close_code": 1007},
    },
    "market_closed": {
        "async_persistable": True,
        "code": "market_closed",
        "http_status": 422,
        "public_detail": "Market is not accepting orders.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async", "origin_http", "websocket"],
        "title": "Market closed",
        "urn": "urn:agara:problem:market-closed",
        "websocket": {"action": "none", "close_code": None},
    },
    "market_not_found": {
        "async_persistable": False,
        "code": "market_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Market not found",
        "urn": "urn:agara:problem:market-not-found",
        "websocket": None,
    },
    "method_not_allowed": {
        "async_persistable": False,
        "code": "method_not_allowed",
        "http_status": 405,
        "public_detail": "This route does not support the requested method.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Method not allowed",
        "urn": "urn:agara:problem:method-not-allowed",
        "websocket": None,
    },
    "order_expiration_too_soon": {
        "async_persistable": False,
        "code": "order_expiration_too_soon",
        "http_status": 422,
        "public_detail": "Good-til-date orders must expire at least 30 seconds from now.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Order expiration too soon",
        "urn": "urn:agara:problem:order-expiration-too-soon",
        "websocket": None,
    },
    "order_funding_failed": {
        "async_persistable": True,
        "code": "order_funding_failed",
        "http_status": None,
        "public_detail": "Order not successful, please try again.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async", "websocket"],
        "title": "Order funding failed",
        "urn": "urn:agara:problem:order-funding-failed",
        "websocket": None,
    },
    "order_not_cancellable": {
        "async_persistable": False,
        "code": "order_not_cancellable",
        "http_status": 409,
        "public_detail": "The order is no longer cancellable.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Order cannot be cancelled",
        "urn": "urn:agara:problem:order-not-cancellable",
        "websocket": None,
    },
    "order_not_fillable": {
        "async_persistable": True,
        "code": "order_not_fillable",
        "http_status": 422,
        "public_detail": "Order cannot be filled right now.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async", "origin_http", "websocket"],
        "title": "Order cannot be filled",
        "urn": "urn:agara:problem:order-not-fillable",
        "websocket": None,
    },
    "order_not_found": {
        "async_persistable": False,
        "code": "order_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Order not found",
        "urn": "urn:agara:problem:order-not-found",
        "websocket": None,
    },
    "order_price_out_of_range": {
        "async_persistable": False,
        "code": "order_price_out_of_range",
        "http_status": 422,
        "public_detail": "Limit price must be above 0 and below 1 collateral unit.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Order price out of range",
        "urn": "urn:agara:problem:order-price-out-of-range",
        "websocket": None,
    },
    "order_size_above_maximum": {
        "async_persistable": False,
        "code": "order_size_above_maximum",
        "http_status": 422,
        "public_detail": "Maximum market sell size is 100,000 shares.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Order size above maximum",
        "urn": "urn:agara:problem:order-size-above-maximum",
        "websocket": None,
    },
    "order_size_below_minimum": {
        "async_persistable": False,
        "code": "order_size_below_minimum",
        "http_status": 422,
        "public_detail": "Minimum market sell size is 1 share.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Order size below minimum",
        "urn": "urn:agara:problem:order-size-below-minimum",
        "websocket": None,
    },
    "order_submission_failed": {
        "async_persistable": True,
        "code": "order_submission_failed",
        "http_status": None,
        "public_detail": "Order could not be submitted, please try again later.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async", "websocket"],
        "title": "Order submission failed",
        "urn": "urn:agara:problem:order-submission-failed",
        "websocket": None,
    },
    "order_value_above_maximum": {
        "async_persistable": False,
        "code": "order_value_above_maximum",
        "http_status": 422,
        "public_detail": "Maximum order value is $100,000.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Order value above maximum",
        "urn": "urn:agara:problem:order-value-above-maximum",
        "websocket": None,
    },
    "order_value_below_minimum": {
        "async_persistable": False,
        "code": "order_value_below_minimum",
        "http_status": 422,
        "public_detail": "Minimum order value is $0.10.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Order value below minimum",
        "urn": "urn:agara:problem:order-value-below-minimum",
        "websocket": None,
    },
    "pnl_not_ready": {
        "async_persistable": False,
        "code": "pnl_not_ready",
        "http_status": 425,
        "public_detail": "PnL is not available yet.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "retry"},
        "representations": ["origin_http"],
        "title": "PnL not ready",
        "urn": "urn:agara:problem:pnl-not-ready",
        "websocket": None,
    },
    "pnl_unavailable": {
        "async_persistable": False,
        "code": "pnl_unavailable",
        "http_status": 503,
        "public_detail": "PnL is unavailable for this wallet.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "PnL unavailable",
        "urn": "urn:agara:problem:pnl-unavailable",
        "websocket": None,
    },
    "post_only_would_cross": {
        "async_persistable": True,
        "code": "post_only_would_cross",
        "http_status": 422,
        "public_detail": "The order would execute immediately instead of resting.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async", "origin_http", "websocket"],
        "title": "Post-only order would cross",
        "urn": "urn:agara:problem:post-only-would-cross",
        "websocket": None,
    },
    "price_feed_not_found": {
        "async_persistable": False,
        "code": "price_feed_not_found",
        "http_status": 422,
        "public_detail": "No price feed is configured for the requested security and provider.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Price feed not found",
        "urn": "urn:agara:problem:price-feed-not-found",
        "websocket": None,
    },
    "price_service_not_configured": {
        "async_persistable": False,
        "code": "price_service_not_configured",
        "http_status": 503,
        "public_detail": "The price service is not configured on this deployment.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Price service not configured",
        "urn": "urn:agara:problem:price-service-not-configured",
        "websocket": None,
    },
    "price_stream_capacity_exceeded": {
        "async_persistable": False,
        "code": "price_stream_capacity_exceeded",
        "http_status": 503,
        "public_detail": "The shared price-stream symbol limit has been reached.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "retry"},
        "representations": ["origin_http"],
        "title": "Price stream capacity exceeded",
        "urn": "urn:agara:problem:price-stream-capacity-exceeded",
        "websocket": None,
    },
    "price_stream_not_configured": {
        "async_persistable": False,
        "code": "price_stream_not_configured",
        "http_status": 503,
        "public_detail": "Price streaming is not configured on this deployment.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Price stream not configured",
        "urn": "urn:agara:problem:price-stream-not-configured",
        "websocket": None,
    },
    "price_temporarily_unavailable": {
        "async_persistable": False,
        "code": "price_temporarily_unavailable",
        "http_status": 503,
        "public_detail": "The requested price is not available yet.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "retry"},
        "representations": ["origin_http"],
        "title": "Price temporarily unavailable",
        "urn": "urn:agara:problem:price-temporarily-unavailable",
        "websocket": None,
    },
    "profile_not_found": {
        "async_persistable": False,
        "code": "profile_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Profile not found",
        "urn": "urn:agara:problem:profile-not-found",
        "websocket": None,
    },
    "rate_limited": {
        "async_persistable": False,
        "code": "rate_limited",
        "http_status": 429,
        "public_detail": "You are rate limited, please try again later.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "retry_after"},
        "representations": ["edge_http", "origin_http"],
        "title": "Too many requests",
        "urn": "urn:agara:problem:rate-limited",
        "websocket": None,
    },
    "request_body_too_large": {
        "async_persistable": False,
        "code": "request_body_too_large",
        "http_status": 413,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Request body too large",
        "urn": "urn:agara:problem:request-body-too-large",
        "websocket": None,
    },
    "route_not_found": {
        "async_persistable": False,
        "code": "route_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Route not found",
        "urn": "urn:agara:problem:route-not-found",
        "websocket": None,
    },
    "security_not_found": {
        "async_persistable": False,
        "code": "security_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Security not found",
        "urn": "urn:agara:problem:security-not-found",
        "websocket": None,
    },
    "sequence_conflict": {
        "async_persistable": True,
        "code": "sequence_conflict",
        "http_status": 409,
        "public_detail": "Order submission failed, please retry.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async", "origin_http", "websocket"],
        "title": "Sequence conflict",
        "urn": "urn:agara:problem:sequence-conflict",
        "websocket": None,
    },
    "server_restarting": {
        "async_persistable": False,
        "code": "server_restarting",
        "http_status": None,
        "public_detail": "The server is restarting. Reconnect after a short delay.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "retry"},
        "representations": ["websocket"],
        "title": "Server restarting",
        "urn": "urn:agara:problem:server-restarting",
        "websocket": {"action": "reconnect", "close_code": 1012},
    },
    "settlement_divergent": {
        "async_persistable": True,
        "code": "settlement_divergent",
        "http_status": None,
        "public_detail": "Settlement effects do not match the expected operation set.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async"],
        "title": "Settlement requires review",
        "urn": "urn:agara:problem:settlement-divergent",
        "websocket": None,
    },
    "settlements_pending": {
        "async_persistable": False,
        "code": "settlements_pending",
        "http_status": 409,
        "public_detail": "Fills for this market can still settle; payouts are "
        "held until they drain.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "retry"},
        "representations": ["origin_http"],
        "title": "Settlements pending",
        "urn": "urn:agara:problem:settlements-pending",
        "websocket": None,
    },
    "signer_authorization_required": {
        "async_persistable": False,
        "code": "signer_authorization_required",
        "http_status": 424,
        "public_detail": "Complete the wallet approval step, then try again.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Finish wallet setup",
        "urn": "urn:agara:problem:signer-authorization-required",
        "websocket": None,
    },
    "slow_consumer": {
        "async_persistable": False,
        "code": "slow_consumer",
        "http_status": None,
        "public_detail": "The connection was closed because messages were not read quickly enough.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["websocket"],
        "title": "Client is reading too slowly",
        "urn": "urn:agara:problem:slow-consumer",
        "websocket": {"action": "reconnect", "close_code": 4008},
    },
    "stream_subject_not_found": {
        "async_persistable": False,
        "code": "stream_subject_not_found",
        "http_status": None,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["websocket"],
        "title": "Stream subject not found",
        "urn": "urn:agara:problem:stream-subject-not-found",
        "websocket": {"action": "none", "close_code": None},
    },
    "stream_subject_unavailable": {
        "async_persistable": False,
        "code": "stream_subject_unavailable",
        "http_status": None,
        "public_detail": "This stream subject is temporarily unavailable.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["websocket"],
        "title": "Stream subject temporarily unavailable",
        "urn": "urn:agara:problem:stream-subject-unavailable",
        "websocket": {"action": "resubscribe", "close_code": None},
    },
    "subscription_limit_exceeded": {
        "async_persistable": False,
        "code": "subscription_limit_exceeded",
        "http_status": None,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["websocket"],
        "title": "Subscription limit exceeded",
        "urn": "urn:agara:problem:subscription-limit-exceeded",
        "websocket": {"action": "none", "close_code": None},
    },
    "token_not_found": {
        "async_persistable": False,
        "code": "token_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Token not found",
        "urn": "urn:agara:problem:token-not-found",
        "websocket": None,
    },
    "trading_day_not_found": {
        "async_persistable": False,
        "code": "trading_day_not_found",
        "http_status": 404,
        "public_detail": "No trading-day coverage exists for the requested date.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Trading day not found",
        "urn": "urn:agara:problem:trading-day-not-found",
        "websocket": None,
    },
    "unsupported_media_type": {
        "async_persistable": False,
        "code": "unsupported_media_type",
        "http_status": 415,
        "public_detail": "Send the request body as application/json.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Unsupported media type",
        "urn": "urn:agara:problem:unsupported-media-type",
        "websocket": None,
    },
    "unsupported_websocket_data": {
        "async_persistable": False,
        "code": "unsupported_websocket_data",
        "http_status": None,
        "public_detail": "Send WebSocket messages as JSON text frames.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["websocket"],
        "title": "Unsupported WebSocket data",
        "urn": "urn:agara:problem:unsupported-websocket-data",
        "websocket": {"action": "none", "close_code": 1003},
    },
    "validation_failed": {
        "async_persistable": False,
        "code": "validation_failed",
        "http_status": 422,
        "public_detail": "One or more fields are invalid.",
        "public_detail_policy": "allowlisted_typed",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Request validation failed",
        "urn": "urn:agara:problem:validation-failed",
        "websocket": None,
    },
    "value_cap_exceeded": {
        "async_persistable": False,
        "code": "value_cap_exceeded",
        "http_status": 422,
        "public_detail": "Order value exceeds the configured maximum cap.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Value cap exceeded",
        "urn": "urn:agara:problem:value-cap-exceeded",
        "websocket": None,
    },
    "venue_not_found": {
        "async_persistable": False,
        "code": "venue_not_found",
        "http_status": 404,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Venue not found",
        "urn": "urn:agara:problem:venue-not-found",
        "websocket": None,
    },
    "wallet_not_registered": {
        "async_persistable": False,
        "code": "wallet_not_registered",
        "http_status": 404,
        "public_detail": "Finish wallet registration and then retry.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "Wallet not registered",
        "urn": "urn:agara:problem:wallet-not-registered",
        "websocket": None,
    },
    "wallet_setup_failed": {
        "async_persistable": True,
        "code": "wallet_setup_failed",
        "http_status": None,
        "public_detail": "Wallet setup did not complete successfully.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async"],
        "title": "Wallet setup failed",
        "urn": "urn:agara:problem:wallet-setup-failed",
        "websocket": None,
    },
    "wallet_setup_incomplete": {
        "async_persistable": False,
        "code": "wallet_setup_incomplete",
        "http_status": 424,
        "public_detail": "Finish wallet registration and then retry.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http", "websocket"],
        "title": "Wallet setup incomplete",
        "urn": "urn:agara:problem:wallet-setup-incomplete",
        "websocket": {"action": "none", "close_code": 1008},
    },
    "wallet_setup_outcome_unknown": {
        "async_persistable": True,
        "code": "wallet_setup_outcome_unknown",
        "http_status": None,
        "public_detail": "Wallet setup may have been submitted and requires reconciliation.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["async"],
        "title": "Wallet setup outcome is uncertain",
        "urn": "urn:agara:problem:wallet-setup-outcome-unknown",
        "websocket": None,
    },
    "websocket_message_too_large": {
        "async_persistable": False,
        "code": "websocket_message_too_large",
        "http_status": None,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["websocket"],
        "title": "WebSocket message too large",
        "urn": "urn:agara:problem:websocket-message-too-large",
        "websocket": {"action": "none", "close_code": 1009},
    },
    "websocket_protocol_error": {
        "async_persistable": False,
        "code": "websocket_protocol_error",
        "http_status": None,
        "public_detail": "The WebSocket protocol state is invalid.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["websocket"],
        "title": "WebSocket protocol error",
        "urn": "urn:agara:problem:websocket-protocol-error",
        "websocket": {"action": "none", "close_code": 1002},
    },
    "websocket_upgrade_required": {
        "async_persistable": False,
        "code": "websocket_upgrade_required",
        "http_status": 426,
        "public_detail": "This route requires a WebSocket upgrade.",
        "public_detail_policy": "allowlisted_static",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http"],
        "title": "WebSocket upgrade required",
        "urn": "urn:agara:problem:websocket-upgrade-required",
        "websocket": None,
    },
    "wrong_credential_type": {
        "async_persistable": False,
        "code": "wrong_credential_type",
        "http_status": 401,
        "public_detail": None,
        "public_detail_policy": "omit",
        "recovery": {"strategy": "none"},
        "representations": ["origin_http", "websocket"],
        "title": "Wrong credential type",
        "urn": "urn:agara:problem:wrong-credential-type",
        "websocket": {"action": "none", "close_code": 1008},
    },
}
